# Generated by Django 4.0.4 on 2022-04-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmsapp', '0002_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('number', models.IntegerField(max_length=13)),
            ],
        ),
    ]
