# Generated by Django 4.0.4 on 2022-04-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerr',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customerr',
            name='number',
            field=models.IntegerField(),
        ),
    ]
